print('Today you will talk to a robot.')
input('Are you ready? ')
print('Hi! My name is Isaac.')
your_name = input('What is your name? ')
name_message = 'Hello, {n}! It is very nice to meet you. '.format (n=your_name)  
input(name_message)
your_color = input('What is your favorite color, {n}? '.format (n = your_name))
color_message = 'That is cool, because I like {c} too!'.format (c = your_color)
print(color_message)
your_grade = input("I'm in third grade, what about you? ")
grade_message = 'I heard {g} grade is so much fun. You are lucky.'.format (g = your_grade)
print(grade_message)
print('It was nice meeting you, {n}. I hope we see each other again. Until then, Goodbye.'.format (n=your_name))